name = "OpenXL"
uuid = "5439f3e2-bb62-4031-b438-a07447f64eb9"
version = "3.2.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LibZip = "89089acc-ee81-44d2-83aa-3aa2951b1031"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serde = "db9b398d-9517-45f8-9a95-92af99003e0e"

[compat]
Serde = "3.0"
LibZip = "1.0"
julia = "1.8"
