name = "OpenXL"
uuid = "5439f3e2-bb62-4031-b438-a07447f64eb9"
version = "2.1.1"

[deps]
Serde = "db9b398d-9517-45f8-9a95-92af99003e0e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
ZipFile = "0.10"
Serde = "3.0"
julia = "1.8"
